### ISSUE TITLE
Unable to get the size of the image

### ISSUE THREAD

**Issue by nzurita** [whiteoctober/WhiteOctoberTCPDFBundle#44]
Hello, I'm rendering and html template via `writeHTML()` method. I get this error:

> TCPDF ERROR: [Image] Unable to get the size of the image: https://example.com/image.jpg

(The image is accesible and visible if I paste the adress in the browser)

`Curl` and `allow_url_fopen` are enabled so I read a possible issue may be write permissions on temporal folder, could this be the case? Which is this folder then?

Any other ideas?

Thank you

**Comment by sampart** [comment]
Hi @nzurita, sorry you're having issues.

I guess this is a TCPDF question rather than a WhiteOctoberTCPDFBundle question, but the [original TCPDF project](https://github.com/tecnickcom/tcpdf) (which this bundle uses) is no longer supported and so you can't raise an issue there.  So I'll see if I can help.

TCPDF puts its cached images into the folder defined by the constant `K_PATH_CACHE` (see  [getObjFilename merthod](https://github.com/tecnickcom/TCPDF/blob/master/include/tcpdf_static.php#L296), called from the [Image function](https://github.com/tecnickcom/TCPDF/blob/master/tcpdf.php#L6869)).

That constant gets its value from `php.ini`'s [`upload-tmp-dir`](http://php.net/manual/en/ini.core.php#ini.upload-tmp-dir) value if set, or [`sys_get_temp_dir()`](http://php.net/manual/en/function.sys-get-temp-dir.php) if that value isn't set.

Therefore, I'd recommend that you do these in order

1. See whether `upload-tmp-dir` is set in `php.ini` and - if set - whether it's writeable by the user your app is running as
2. Look at the output of `sys_get_temp_dir()` on your system and see whether that's writeable by the user your app is running as
3. If you can't change the permissions on the directories identified in the previous steps, try setting the `K_PATH_CACHE` value to refer to a directory the relevant user can write to.

Hope this helps.  Sorry for the belated response.

**Comment by sampart** [comment]
Hi again.  I missed something here, sorry.  Turns out this issue does relate to the bundle itself rather than just TCPDF.

I hadn't realised (I'm not the original developer) that the WhiteOctoberTCPDFBundle overrides the default value of `k_path_cache`.  It sets it to: `'%kernel.cache_dir%/tcpdf'` (see [here](https://github.com/whiteoctober/WhiteOctoberTCPDFBundle/blob/master/DependencyInjection/Configuration.php#L51)).

This makes me wonder if you need to look at the permission settings of your Symfony cache folder.  This documentation page might help: http://symfony.com/doc/3.4/setup/file_permissions.html

Let us know how you get on!

**Comment by nzurita** [comment]
Hello, sorry for the late response, I solved it some time ago but I think I solved it as you propose, located the cache dir and give proper permissions.

Thank you

**Comment by sampart** [comment]
No problem, glad you got it sorted, @nzurita!
